# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Preschool
    url: 'https://www.brighthubeducation.com/preschool/'
    weight: 10
  - name: Elementary
    url: 'https://www.brighthubeducation.com/elementary-school/'
    weight: 30
  - name: Middle
    url: 'https://www.brighthubeducation.com/middle-school/'
    weight: 60
  - name: High
    url: 'https://www.brighthubeducation.com/high-school/'
    weight: 90
  - name: Special Ed
    url: 'https://www.brighthubeducation.com/special-education/'
    weight: 95
  - name: Homeschool
    url: 'https://www.brighthubeducation.com/homeschool/'
    weight: 100
  - name: More
    identifier: more
    weight: 140
  - name: Summer Learning
    parent: more
    url: 'https://www.brighthubeducation.com/summer-learning/'
    weight: 130
  - name: Teaching Tools
    parent: more
    url: 'https://www.brighthubeducation.com/teaching-tools/'
    weight: 130
  - name: Second Languages
    parent: more
    url: 'https://www.brighthubeducation.com/second-languages/'
    weight: 130
  - name: Teaching ESL Learners
    parent: more
    url: 'https://www.brighthubeducation.com/teaching-esl-learners/'
    weight: 130
