# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Preschool
    url: 'https://www.brighthubeducation.com/preschool/'
    weight: 10
  - name: Elementary
    url: 'https://www.brighthubeducation.com/elementary-school/'
    weight: 30
  - name: Middle
    url: 'https://www.brighthubeducation.com/middle-school/'
    weight: 60
  - name: High
    url: 'https://www.brighthubeducation.com/high-school/'
    weight: 90
  - name: Special Ed
    url: 'https://www.brighthubeducation.com/special-education/'
    weight: 120
